export const Gents = {
    title:"Gents Fashion",
    image1: "images/men/1.jpg",
    image2: "images/men/2.jpg",
    image3: "images/men/3.jpg",
    image4: "images/men/4.jpg",
    image5: "images/men/5.jpg",
    image6: "images/men/6.jpg",
    price1: "559 INR",
    price2: "459 INR",
    price3: "659 INR",
    price4: "759 INR",
    price5: "859 INR",
    price6: "959 INR",
}
export const Ladies = {
    title:"Women Fashion",
    image1: "images/women/1.jpg",
    image2: "images/women/2.jpg",
    image3: "images/women/3.jpg",
    image4: "images/women/4.jpg",
    image5: "images/women/5.jpg",
    image6: "images/women/6.jpg",
    price1: "559 INR",
    price2: "459 INR",
    price3: "659 INR",
    price4: "759 INR",
    price5: "859 INR",
    price6: "959 INR",
}